### ISSUE TITLE
[suggestion] Add default/recommended servers list section to version Config.

### ISSUE THREAD

**Issue by leagris** [ATLauncher/ATLauncher#315]
### Todo:
- [ ] Add a new Configs section about servers list.
- [ ] If `servers.dat` exists, load its content and merge with servers list from Configs section.
- [ ] Wirte-back `servers.dat` with new or updated servers list.

#### Configs.xml

```XML
<version>
    <servers>
        <server icon = "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAASRklEQVR42u1beVzVxRa/O/dygcsmogiioimb5oILggIpCAqIhLK4Aiq4ZmCpmYniKzUVBNeyRVPb8KmFmtarzOWlplavXHFDIVFzy9TszTtnfmcuP25Igtr7I/x8vp977+83M+fMd86cOecMKhhjir8zFPUE1BNQT0A9AfUE/J0JsPg3HrATwB4xSgBvAQIVNf97XPJ/BmyqSb4bNWB/AWb8n+Uvqo71Cnyp09mxbt0WsYEDj7BBg46yxMSjLCnpKEtJeTjExu5gPj7plUooNTmOjdarASqFQjnhcctPSNhXVb5C9W6lfHro7h7B+vf/mgvFTkOHHmMjRhxnI0eeYKNGnWAZGSc5MjNrB9Fv9OgTrG/ft4QS99Raz46gyEePW75ch7i4fzIrKxOXp1RaZwMBVgrBOjKenCwJTk8/wcaOPcmeeaaEPffcaTZt2hk2ffoZ9uKLdccLL5xhU6acZv7+iUSC8rJY9cDAPD7xv0J+dHQhEaD7GghwVAjWBw8+xlJTj7MxY06yrKxTvNPLL5eyhQvPs8LCMrZ0aRlbvry8zliypIzl51+A1VxnNkUvr0iQu59PGpGW9njlL158gc2fX8ocHDy4fJ0+YKDiUToYV1dPFh8/ga1a9Q0rLr7Ctm79mW3bJmHLlits06bLQMJ+c3t7e49HJhvl5uV9VkXuJ5/8zLZvlz7x2ebNl9l771WwyMhxvI9G67VMQUfEI/e2+fkb2ddf32AHDtxkhw5J2L//Bnv33cNiD14ih3T9UcpNSXmG/fvfN7gslPndd7+w77+X8M03N9muXdfBt8yQCNA9sUkB+0CPewHQTAyybFkZW7u2gn300RX26adX2VdfXWO7d19nbm6e/L3J+eViaL8esBbwDmANYLWNw7PbtFb+eOazNm2e5Ar88MMtduLEr+zMmdvs1Knb7IMPdvExVGrnclvHKdOhXwSgE6BdXeWjXJ2+yxHRf9iwSXzCx49LcktL77ALF+7wT9Rl2rR8QcBeJMAa4AxoIQbA/bJmzUW2ceNlbkJffHGNM9e4saSAnfOcDdD+NcBSwGLAIsBC+swX4+BKoCIlJb9yBSoq7rKpU3Np/3X+EdpOAyQAegA6P4T8PJRr4zChCN/b2tpDn1J27NgtPulLl35j167dY9ev3+Pfc3ML+DhaK9/DwgLsAU2EAq+8UsqVePvti6yo6BLfVzt2XGWNGpECTjmvGe0zXtcZuhZb2yYVOjRcOR76j0LYOEyahW2MRnv28cdX+OohCUKRHj3C+BhG0+g90H4OYDCgJ6B9beRD+5cAkwEoO5MwQakyXsE2a9Yc4tsAV/zixbvsxo177Pbt39kvv/zOxo3L5uNYWffahwToADZoBUIBPHKEEmiKuBLoxIQCoPxK+b5TKq1K9caoMTBGsErtsg2fde2awl57rZxPAEk4evQW27v3CJm/4x0H17c+hvavEAHBAJ8HlW/nNAOtLQMwCBAFCAOEAHqBLuXYZsGCfZy4fftucAtE8m/d+p2TEBMTz8exthvyFRKgISuwEQo8++wpNnPmWX5soQIo/PPPr5lNUGfovh0/g4MzmadndxkR+i8wyMHvGRlf8mPs9dfLuSLoD5KSUsXxcxnk/ROQS5PoAmj+oPKBANxqwwDhgA6AJ7A/HWv8mFuw4Dy3IDwB0BGeP3+HW0FZ2SU4fRwkX9Jg0WYkQEVhoVYogEEIBh+LFl0Ar13BPvvsKt/PwgkZ7TPfFG09PAJZ27ajYN+5m4lo3XoQHwODj7y8C+zDDy/BGbxJBED/hT18EOStIx8QA/AHuD6ofDunlwrIcoIALcmH2SoU6t34vkOHUdyKkECUjX3RAV+9eo8VFCyT9r/O5yr0eU+RkHDEDKEAhp4YNaHyGzZcZnv2XOf7uEmTZmIPrgTzyQVzOyf6PPlkFvP2roy327UbxaM4XIlVq46bV09vjCwFwZ8AVgDGkfl6AUy1kU8WEAhoKlmvMg/f2di484AOrQi30TvvXORbEH3B5cu/sWbNmkvmbxpRgidItQRg3IwM4h5E8zt8+CZn0MODFHCejcdPhr3LkgjwpKNEv1atBkK8X2S2BldXP1jJ3axLl2gKPFpegn47kHnAy7SKndEBA4y1lD+anGcz2Hq5om/v3kVs+PDjPIyeM+ccP0127pQIWLBgqQiAbkO/nXiSVEsAJhAYimIIid4Xz3LcQ02bCgXmvE/etzegtVrTJFnsfTR/XMGWLSNZVUep/9XUYCE6PszE0IQnkQPzIRO2qqV8bj0qlf0boh/mNJg9YkidnX2Kh724hTCGOHiwzLz3jaa0C9B3Kx7dD0tALyQA4KLRte4sSOjadTJXICgow0yAwSZemH0+YCogiZyfB+5fdMa1kW/nPOsFmPw+0adnz1U8p8GcAn0I9kcLwvAXI0A/v/Z09vvfAln7KJB68WEIGEcEPEEraKfWuCZW7uMvIeA4B0rNlZEQuxHaPU/7N4zI46tPufkDy4ds7ib35CZ3vu1w5XHyaH3oe1599Tw/QTCI6tYtlPeDFPyOvcviYyBrO6AQY4eHJeAp8sIYShthK4SDY+RxQHj4HE4AeuKhQ+ebSUDnSeFvW0BjikHwKFY+qHxru5R/4aePTxQbPfogrxuIyaPl4fG7atVP4AM2wMnRjGIPl7t2zv84BXJ2UeiOYfjTdSLgz4BFh5Ejv2CzZp3lnnzlynLWp89YSRGV6QcQ3A1DbyKOr35t5OsMgd9KDm8Kd3Y4cSy44OTR8WEAhqY/ZkyOWSeNzvumvUs+Hr9FgLmAVHSij5QAR0cf5us7EpKRAzynz8mRCECFcEWcnZvSBLplYeACcKBIVFkb+UZT6nbRNiBgNBs/voTLmz37HO+DkSM6Pow+i4v3mPsplYY7cPyhI55IDtivVgRgQoMZFu4rjLKQ7UmTTvEKjihqoDliUQP3Ib4Xic369RUsIWE67cWm6IC8AQ0ABgzEarsFDbbxy+UkYPuCgguQbUqh95EjUh9MwH78sZxFRMRVWoPWa4twwA9MAE6+vPwuj6uRXTxecHWxHZohThq974QJJWzy5MrVX71ayuowHM7JKRK5wHcgvCvAEwMgjEJr4wPEKWSwicsSfXr0yORWhoUPDLvPnbvN438MfjARw0AqLe2lymNZZdyl03cMqhUByCYOjMcKZnpvvvkTD1fR2c2YcZYDJ44RGK4GTh5zegxEMBxNTp5IuUBHPIP7AnzxCKVcRFWHYzjSyrp3uugXFTWOp88i9r9y5TcO/I4E4Fg5Odthq5orUfcemICysjuczZ9+usv3FubnOLl16yo48ytWlHNnh8kPThxjcCxL7d17HT6/Z4MGpZrZN9qPeZuiQDRDdzxB6khAH0BHK+vQ4fLSGKbBp09LFoAEoO6oM24N1Gv+/COsY8ckoU+Vfzsf76WE8r+2Dtk7qXiSTmlwM4wh0A88iHw4yzGJWUbpcC86TtvILaEW+vxuSYCvQqHa9agnDnv+tk7f6ZKdcy5GYO/LjiFLAmqUj5OHTBBziXkUTAVTIIbRZCtItDIhOjzyZ/ooldpfIWg7BKfJyD/cUdF+bEjMRgOyqOyEMfwWiqKKKZ9/n9JaURdcQ9/X0zts8zHF3cWUBC0BTAEMBATQFrAhAmqSL8ZeQtHkADR/mrwz+ZIniBQMs5+jUtkaOvs3kK5oPbMAWMDpXx0BOgpQWlK+nUJKzKE4fimFkaIWJ+qBC2V1wTxqW0AKF9KzOTQW7v9QNF1S3CCuqWqQPxOQQxMbShWg1tTfhvwIHqutKE0eQGWy6WRxqNurgNlUSkMLjK6OAA0N6EoKBtFKIKsjACPrANzvwwGJgH40JmaBbmT+OjoGa5KfQFYTQ0VUX4v+GlmBF4Os9pRv9Ackk/zhRP7T5EADqyNAReGpiZRoSeYYQMwG1QHd6dxHk/WjMNiVZOipIqX8E/kdCW1plRtTMVcPPqYJ+I6BkCAlwvmeolI7DVdr3EdrdK0mGO0zwkj3bqRHN/rdDi0IZQ6mu3t+hw+xuhESmphKZ6Teo1Bq9or7NIR0w6v9Vqmyex2EjBDP5O/5d5XxA+h/9j4e+BRdjlZzMaP8ij5PQ/9DMM4KmnBjiCIHc52kSxXQUT1R3C7XGtK8/vDirb/onr6WymoLlCrbuPu9x9vl6oCXrzWO6+DgA0FBDkRR26u88Pd/lt/T43scCIsNHh4RrG3bLP49PLzI3FY8w1te+Xcvr4EsOnoHv/UVsPybAby7t7zPDwt7w9wmMlLIUR6A1Z4n1w0rQFJhNoLrExFRxNsjoqKKWFzcpzw5E3kKXgAj5HIUbdqks5CQN7jS4o8IdDoTCNjHgoPz+G8sOCDwOdb94uM/g4ltMBPQoUMWF9CjRx7/jjW5kJB8yP58gZCRvE1YWD4vVQUEZJv74ftOnbL5c/xuuTqxsRtYTIyQoz4IW3OhKMAimUFBeWZ9e/bMg4XMNt//i7S8efM+rE2bQfz30KEH+N8b4DOZHBFHF/GJYSdUEhtjcRMbY77dokVlp4SEjRzid5cuk3mb3r0X83IYpqeRkQVVJoO/MVHq3n2y2H+8ohwYOJk/R/Tvv5r5+SWa+yQmboIQehOT+ZxCQfiwYcc4yfLJ9uyZy4YM+fwP9UgBLJ5MnFgCixgp6pRgVQoVv8tzcvLlkwgJyeUNhaIpKZtgUFHTV3OHNXz4ZiBoM0w8g6e9CMwAY2IKWWjo8zwpSkhYSlGgE16WsAEDlvBKb1jY8xTVeayTLON5fn/QqJGfZYjKUlM/4rJkN1D78bNz52wz4ZaTRJ2mTj0N2yNDNpb6Bn6fNOkwl+XtHSXuJ19SSBci6v1iNbCqkpX1Lax8d5jkWl5kcHPzEynkMfwcN64Y0t9is9Dw8Ck8909OXgZbZSqvAaSnr5AmqnHjYw8ZspzfEeB7qULTerNkeVPZvHmlrEkT/z9MZvz4qnIEUE9Mwfv1k/7aAxObxo39mMFg4hD6BAQki4W7KV25fc/mzi2FbdlX3A3mcwJUaucEfmmhN/HJ4wChoWN4qpuaulyUsk6CCfKr76ysraDAFrNC0dHTeO0PJ/300y/wYmRMzHgRv3+Hn2lpK/hferRv349uZry34Ge/ftO4HAS+nz17L+z9acza2sTlYHET02vEiBFr+cqGhDzHVzIwMIPXAZBYBLZFiN8ZGeurEDBz5n8gdf+Bj033C1nmyEsUM1EAsiiZ/zzm6dmWylhBH8Cq7fiz46phw6bmwofE8lPbJE/tz5KS5olk5IbBJq6wrkci3v0NG7a2stAKE6oOlclYA26FISGZfGEly2z8LV6uKCgKM2i0zSNryObOQptnMKzVaL22wnkM1mB7QqNttllv7DsP3h+jP3ookffTGbrvxsQD3p+pUjS1DsOrrVS9TfSrkL39WDVTM1RAsLNLkmNXZTwsqEL7/VWf3T/7U6kdjmqt/DdY2yZOt3xnbTcUb6bSROiJsbSd1so3FvbsQpjUWCtDUL5G2+JLvTFiDU0es6chgDiKo58i9KXYGuPtdEh7t6k1jU7q9F0/h98zKHlJw/EgPP1EZwjEZCmeYvtYrOpQmbwP/U6kmD+e4vgoahNLOUG4RttyNUz8EFgkXpElmBrMHwvINDWYm25ynptGSKX8BceLNdj0nwTtIXJtvcpgEz+ZbqUHIgFKWfztQJeN7ShbG0DZ2BAaqC8lIhhLP0noSplZb1IwmZKfUZQIDaHnIbK8oAf97k5jdaLPYLryDqdiRxi1DSaye1G/MJLXm5KreFqYGAvE0mcvymM6UxUqkMYIlSdBasqmnIgEP1IwjISH0AA+dJvrSe286JlIWIJJoJhIKE3Oj9p503d/+t6KxmhJvwWx7WhMX0I7et6WMj2RHHUlmSLRkUM860BjtKEU2luMLydASdVZI+XjbjKlfKhzc0pKGhBRjvS9EbVvatHHV9bPndq40W2wO43lSjm9C43jQeN4EJoQmhLpnjReC0Ir2cRaUVFEoLX44wkay41kuonxq0uFtVSgsJNVWhoSnOi5kdroyWqMlMPb0TaS93MhouwpxRWwp/Y2Moj+jjI4UFtHku9E4zcguBCJQkdXCzSk9g4W8vm4lgQo5X8xQhM0yKCn5xpqI6AhaMmh6i36WtFzOcQzrWxMLT23ko1hVc0zuU5iAaxl340Wz/TV6GBFV/KK6ooiShkZllCK4sX9/sn6K+V9anquqOW/asa6nxxlTX3q/8dIPQH1BNQTUE9APQH1BPx98T89wJBG5tQRjwAAAABJRU5ErkJggg==" ip = "br.beyondrealitypack.com" name = "Beyond Reality" />
        <server ip "138.201.134.44:25560" name = "Dirt Huts" />
    </servers>
</version>
```

#### Configs.json
```JSON
{
    "servers": [
        {
            "icon": "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAASRklEQVR42u1beVzVxRa/O/dygcsmogiioimb5oILggIpCAqIhLK4Aiq4ZmCpmYniKzUVBNeyRVPb8KmFmtarzOWlplavXHFDIVFzy9TszTtnfmcuP25Igtr7I/x8vp977+83M+fMd86cOecMKhhjir8zFPUE1BNQT0A9AfUE/J0JsPg3HrATwB4xSgBvAQIVNf97XPJ/BmyqSb4bNWB/AWb8n+Uvqo71Cnyp09mxbt0WsYEDj7BBg46yxMSjLCnpKEtJeTjExu5gPj7plUooNTmOjdarASqFQjnhcctPSNhXVb5C9W6lfHro7h7B+vf/mgvFTkOHHmMjRhxnI0eeYKNGnWAZGSc5MjNrB9Fv9OgTrG/ft4QS99Raz46gyEePW75ch7i4fzIrKxOXp1RaZwMBVgrBOjKenCwJTk8/wcaOPcmeeaaEPffcaTZt2hk2ffoZ9uKLdccLL5xhU6acZv7+iUSC8rJY9cDAPD7xv0J+dHQhEaD7GghwVAjWBw8+xlJTj7MxY06yrKxTvNPLL5eyhQvPs8LCMrZ0aRlbvry8zliypIzl51+A1VxnNkUvr0iQu59PGpGW9njlL158gc2fX8ocHDy4fJ0+YKDiUToYV1dPFh8/ga1a9Q0rLr7Ctm79mW3bJmHLlits06bLQMJ+c3t7e49HJhvl5uV9VkXuJ5/8zLZvlz7x2ebNl9l771WwyMhxvI9G67VMQUfEI/e2+fkb2ddf32AHDtxkhw5J2L//Bnv33cNiD14ih3T9UcpNSXmG/fvfN7gslPndd7+w77+X8M03N9muXdfBt8yQCNA9sUkB+0CPewHQTAyybFkZW7u2gn300RX26adX2VdfXWO7d19nbm6e/L3J+eViaL8esBbwDmANYLWNw7PbtFb+eOazNm2e5Ar88MMtduLEr+zMmdvs1Knb7IMPdvExVGrnclvHKdOhXwSgE6BdXeWjXJ2+yxHRf9iwSXzCx49LcktL77ALF+7wT9Rl2rR8QcBeJMAa4AxoIQbA/bJmzUW2ceNlbkJffHGNM9e4saSAnfOcDdD+NcBSwGLAIsBC+swX4+BKoCIlJb9yBSoq7rKpU3Np/3X+EdpOAyQAegA6P4T8PJRr4zChCN/b2tpDn1J27NgtPulLl35j167dY9ev3+Pfc3ML+DhaK9/DwgLsAU2EAq+8UsqVePvti6yo6BLfVzt2XGWNGpECTjmvGe0zXtcZuhZb2yYVOjRcOR76j0LYOEyahW2MRnv28cdX+OohCUKRHj3C+BhG0+g90H4OYDCgJ6B9beRD+5cAkwEoO5MwQakyXsE2a9Yc4tsAV/zixbvsxo177Pbt39kvv/zOxo3L5uNYWffahwToADZoBUIBPHKEEmiKuBLoxIQCoPxK+b5TKq1K9caoMTBGsErtsg2fde2awl57rZxPAEk4evQW27v3CJm/4x0H17c+hvavEAHBAJ8HlW/nNAOtLQMwCBAFCAOEAHqBLuXYZsGCfZy4fftucAtE8m/d+p2TEBMTz8exthvyFRKgISuwEQo8++wpNnPmWX5soQIo/PPPr5lNUGfovh0/g4MzmadndxkR+i8wyMHvGRlf8mPs9dfLuSLoD5KSUsXxcxnk/ROQS5PoAmj+oPKBANxqwwDhgA6AJ7A/HWv8mFuw4Dy3IDwB0BGeP3+HW0FZ2SU4fRwkX9Jg0WYkQEVhoVYogEEIBh+LFl0Ar13BPvvsKt/PwgkZ7TPfFG09PAJZ27ajYN+5m4lo3XoQHwODj7y8C+zDDy/BGbxJBED/hT18EOStIx8QA/AHuD6ofDunlwrIcoIALcmH2SoU6t34vkOHUdyKkECUjX3RAV+9eo8VFCyT9r/O5yr0eU+RkHDEDKEAhp4YNaHyGzZcZnv2XOf7uEmTZmIPrgTzyQVzOyf6PPlkFvP2roy327UbxaM4XIlVq46bV09vjCwFwZ8AVgDGkfl6AUy1kU8WEAhoKlmvMg/f2di484AOrQi30TvvXORbEH3B5cu/sWbNmkvmbxpRgidItQRg3IwM4h5E8zt8+CZn0MODFHCejcdPhr3LkgjwpKNEv1atBkK8X2S2BldXP1jJ3axLl2gKPFpegn47kHnAy7SKndEBA4y1lD+anGcz2Hq5om/v3kVs+PDjPIyeM+ccP0127pQIWLBgqQiAbkO/nXiSVEsAJhAYimIIid4Xz3LcQ02bCgXmvE/etzegtVrTJFnsfTR/XMGWLSNZVUep/9XUYCE6PszE0IQnkQPzIRO2qqV8bj0qlf0boh/mNJg9YkidnX2Kh724hTCGOHiwzLz3jaa0C9B3Kx7dD0tALyQA4KLRte4sSOjadTJXICgow0yAwSZemH0+YCogiZyfB+5fdMa1kW/nPOsFmPw+0adnz1U8p8GcAn0I9kcLwvAXI0A/v/Z09vvfAln7KJB68WEIGEcEPEEraKfWuCZW7uMvIeA4B0rNlZEQuxHaPU/7N4zI46tPufkDy4ds7ib35CZ3vu1w5XHyaH3oe1599Tw/QTCI6tYtlPeDFPyOvcviYyBrO6AQY4eHJeAp8sIYShthK4SDY+RxQHj4HE4AeuKhQ+ebSUDnSeFvW0BjikHwKFY+qHxru5R/4aePTxQbPfogrxuIyaPl4fG7atVP4AM2wMnRjGIPl7t2zv84BXJ2UeiOYfjTdSLgz4BFh5Ejv2CzZp3lnnzlynLWp89YSRGV6QcQ3A1DbyKOr35t5OsMgd9KDm8Kd3Y4cSy44OTR8WEAhqY/ZkyOWSeNzvumvUs+Hr9FgLmAVHSij5QAR0cf5us7EpKRAzynz8mRCECFcEWcnZvSBLplYeACcKBIVFkb+UZT6nbRNiBgNBs/voTLmz37HO+DkSM6Pow+i4v3mPsplYY7cPyhI55IDtivVgRgQoMZFu4rjLKQ7UmTTvEKjihqoDliUQP3Ib4Xic369RUsIWE67cWm6IC8AQ0ABgzEarsFDbbxy+UkYPuCgguQbUqh95EjUh9MwH78sZxFRMRVWoPWa4twwA9MAE6+vPwuj6uRXTxecHWxHZohThq974QJJWzy5MrVX71ayuowHM7JKRK5wHcgvCvAEwMgjEJr4wPEKWSwicsSfXr0yORWhoUPDLvPnbvN438MfjARw0AqLe2lymNZZdyl03cMqhUByCYOjMcKZnpvvvkTD1fR2c2YcZYDJ44RGK4GTh5zegxEMBxNTp5IuUBHPIP7AnzxCKVcRFWHYzjSyrp3uugXFTWOp88i9r9y5TcO/I4E4Fg5Odthq5orUfcemICysjuczZ9+usv3FubnOLl16yo48ytWlHNnh8kPThxjcCxL7d17HT6/Z4MGpZrZN9qPeZuiQDRDdzxB6khAH0BHK+vQ4fLSGKbBp09LFoAEoO6oM24N1Gv+/COsY8ckoU+Vfzsf76WE8r+2Dtk7qXiSTmlwM4wh0A88iHw4yzGJWUbpcC86TtvILaEW+vxuSYCvQqHa9agnDnv+tk7f6ZKdcy5GYO/LjiFLAmqUj5OHTBBziXkUTAVTIIbRZCtItDIhOjzyZ/ooldpfIWg7BKfJyD/cUdF+bEjMRgOyqOyEMfwWiqKKKZ9/n9JaURdcQ9/X0zts8zHF3cWUBC0BTAEMBATQFrAhAmqSL8ZeQtHkADR/mrwz+ZIniBQMs5+jUtkaOvs3kK5oPbMAWMDpXx0BOgpQWlK+nUJKzKE4fimFkaIWJ+qBC2V1wTxqW0AKF9KzOTQW7v9QNF1S3CCuqWqQPxOQQxMbShWg1tTfhvwIHqutKE0eQGWy6WRxqNurgNlUSkMLjK6OAA0N6EoKBtFKIKsjACPrANzvwwGJgH40JmaBbmT+OjoGa5KfQFYTQ0VUX4v+GlmBF4Os9pRv9Ackk/zhRP7T5EADqyNAReGpiZRoSeYYQMwG1QHd6dxHk/WjMNiVZOipIqX8E/kdCW1plRtTMVcPPqYJ+I6BkCAlwvmeolI7DVdr3EdrdK0mGO0zwkj3bqRHN/rdDi0IZQ6mu3t+hw+xuhESmphKZ6Teo1Bq9or7NIR0w6v9Vqmyex2EjBDP5O/5d5XxA+h/9j4e+BRdjlZzMaP8ij5PQ/9DMM4KmnBjiCIHc52kSxXQUT1R3C7XGtK8/vDirb/onr6WymoLlCrbuPu9x9vl6oCXrzWO6+DgA0FBDkRR26u88Pd/lt/T43scCIsNHh4RrG3bLP49PLzI3FY8w1te+Xcvr4EsOnoHv/UVsPybAby7t7zPDwt7w9wmMlLIUR6A1Z4n1w0rQFJhNoLrExFRxNsjoqKKWFzcpzw5E3kKXgAj5HIUbdqks5CQN7jS4o8IdDoTCNjHgoPz+G8sOCDwOdb94uM/g4ltMBPQoUMWF9CjRx7/jjW5kJB8yP58gZCRvE1YWD4vVQUEZJv74ftOnbL5c/xuuTqxsRtYTIyQoz4IW3OhKMAimUFBeWZ9e/bMg4XMNt//i7S8efM+rE2bQfz30KEH+N8b4DOZHBFHF/GJYSdUEhtjcRMbY77dokVlp4SEjRzid5cuk3mb3r0X83IYpqeRkQVVJoO/MVHq3n2y2H+8ohwYOJk/R/Tvv5r5+SWa+yQmboIQehOT+ZxCQfiwYcc4yfLJ9uyZy4YM+fwP9UgBLJ5MnFgCixgp6pRgVQoVv8tzcvLlkwgJyeUNhaIpKZtgUFHTV3OHNXz4ZiBoM0w8g6e9CMwAY2IKWWjo8zwpSkhYSlGgE16WsAEDlvBKb1jY8xTVeayTLON5fn/QqJGfZYjKUlM/4rJkN1D78bNz52wz4ZaTRJ2mTj0N2yNDNpb6Bn6fNOkwl+XtHSXuJ19SSBci6v1iNbCqkpX1Lax8d5jkWl5kcHPzEynkMfwcN64Y0t9is9Dw8Ck8909OXgZbZSqvAaSnr5AmqnHjYw8ZspzfEeB7qULTerNkeVPZvHmlrEkT/z9MZvz4qnIEUE9Mwfv1k/7aAxObxo39mMFg4hD6BAQki4W7KV25fc/mzi2FbdlX3A3mcwJUaucEfmmhN/HJ4wChoWN4qpuaulyUsk6CCfKr76ysraDAFrNC0dHTeO0PJ/300y/wYmRMzHgRv3+Hn2lpK/hferRv349uZry34Ge/ftO4HAS+nz17L+z9acza2sTlYHET02vEiBFr+cqGhDzHVzIwMIPXAZBYBLZFiN8ZGeurEDBz5n8gdf+Bj033C1nmyEsUM1EAsiiZ/zzm6dmWylhBH8Cq7fiz46phw6bmwofE8lPbJE/tz5KS5olk5IbBJq6wrkci3v0NG7a2stAKE6oOlclYA26FISGZfGEly2z8LV6uKCgKM2i0zSNryObOQptnMKzVaL22wnkM1mB7QqNttllv7DsP3h+jP3ookffTGbrvxsQD3p+pUjS1DsOrrVS9TfSrkL39WDVTM1RAsLNLkmNXZTwsqEL7/VWf3T/7U6kdjmqt/DdY2yZOt3xnbTcUb6bSROiJsbSd1so3FvbsQpjUWCtDUL5G2+JLvTFiDU0es6chgDiKo58i9KXYGuPtdEh7t6k1jU7q9F0/h98zKHlJw/EgPP1EZwjEZCmeYvtYrOpQmbwP/U6kmD+e4vgoahNLOUG4RttyNUz8EFgkXpElmBrMHwvINDWYm25ynptGSKX8BceLNdj0nwTtIXJtvcpgEz+ZbqUHIgFKWfztQJeN7ShbG0DZ2BAaqC8lIhhLP0noSplZb1IwmZKfUZQIDaHnIbK8oAf97k5jdaLPYLryDqdiRxi1DSaye1G/MJLXm5KreFqYGAvE0mcvymM6UxUqkMYIlSdBasqmnIgEP1IwjISH0AA+dJvrSe286JlIWIJJoJhIKE3Oj9p503d/+t6KxmhJvwWx7WhMX0I7et6WMj2RHHUlmSLRkUM860BjtKEU2luMLydASdVZI+XjbjKlfKhzc0pKGhBRjvS9EbVvatHHV9bPndq40W2wO43lSjm9C43jQeN4EJoQmhLpnjReC0Ir2cRaUVFEoLX44wkay41kuonxq0uFtVSgsJNVWhoSnOi5kdroyWqMlMPb0TaS93MhouwpxRWwp/Y2Moj+jjI4UFtHku9E4zcguBCJQkdXCzSk9g4W8vm4lgQo5X8xQhM0yKCn5xpqI6AhaMmh6i36WtFzOcQzrWxMLT23ko1hVc0zuU5iAaxl340Wz/TV6GBFV/KK6ooiShkZllCK4sX9/sn6K+V9anquqOW/asa6nxxlTX3q/8dIPQH1BNQTUE9APQH1BPx98T89wJBG5tQRjwAAAABJRU5ErkJggg==",
            "ip": "br.beyondrealitypack.com",
            "name" : "Beyond Reality"
         },
         {
            "ip": "138.201.134.44:25560",
            "name": "Dirt Huts"
         }
    ]
}
```

**Comment by RyanTheAllmighty** [comment]
Closing this to clean up the issues in the repository.

Use case is small and mods exist to help with showing official/recommended servers.
